### ISSUE TITLE
Player freezes if kill and die at the same time

### ISSUE THREAD

**Issue by the-eduardo** [DasIschBims/BattleBitLifeSteal#4]
In rare occasions, as the API handles deaths and kills simultaneously if someone kill and die at the same instant the player will freeze, without being able to move or shoot.
I think this could be solved using some `await Task.Delay(100);`, not sure

**Comment by Bims-sh** [comment]
This is a known issue, happens when the player despawns too fast. I already tried the await but 100ms is not enough.
This is actually intended game behavior since the ragdoll physics get disabled once the player is fully dead.

Will ask Oki about this though :)

Turns out I misread but should still be fixed, mb.

**Comment by Bims-sh** [comment]
This seems to be mostly fixed after I set the giveuptime on respawns to 5 :)

**Comment by Bims-sh** [comment]
Still there, have to look into it. For now just respawn via the menu

**Comment by Bims-sh** [comment]
Actually fixed!
